name: flutter3_desktop_core
description: "flutter3_desktop_core package."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Desktop
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter3_basics:
    path: ../../Flutter3Core/flutter3_basics
  flutter3_widgets:
    path: ../../Flutter3Core/flutter3_widgets
  flutter3_core:
    path: ../../Flutter3Core/flutter3_core

  # https://pub.dev/packages/window_manager
  # 这个插件允许 Flutter 桌面应用调整窗口的大小和位置。
  # https://pub.dev/packages/path
  # https://pub.dev/packages/screen_retriever
  window_manager: ^0.5.1
  # https://pub.dev/packages/screen_retriever
  screen_retriever: ^0.2.0

  # https://pub.dev/packages/desktop_drop
  # https://pub.dev/packages/cross_file
  # https://pub.dev/packages/flutter_web_plugins
  # https://pub.dev/packages/web
  #desktop_drop: ^0.5.0 #只能支持获取路径, 不支持文本的拖拽

  # https://pub.dev/packages/super_drag_and_drop
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/super_clipboard
  # https://pub.dev/packages/super_native_extensions
  super_drag_and_drop: ^0.9.1
  # https://pub.dev/packages/super_clipboard
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/super_native_extensions
  super_clipboard: ^0.9.1
  super_native_extensions: ^0.9.1
#  super_native_extensions:
#    git:
#      url: git@github.com:FlutterStudioIst/super_native_extensions.git
#      path: super_native_extensions/

  # https://pub.dev/packages/hotkey_manager
  hotkey_manager: ^0.2.3

dependency_overrides:
  # Because flutter3_desktop_core depends on super_native_extensions ^0.9.1 which depends on device_info_plus >=10.0.1 <12.0.0, device_info_plus >=10.0.1 <12.0.0 is required.
  # So, because flutter3_app depends on device_info_plus ^12.3.0, version solving failed.
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # in flutter3_basics
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
